# Generated by Django 5.0.1 on 2025-07-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_productimage_product_category_product_sku_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='store',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
