# Generated by Django 5.0.1 on 2025-07-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_remove_store_created_at_remove_store_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='store_whatsapp_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
