# Generated by Django 5.0.1 on 2025-07-25 17:18

import django.db.models.deletion
import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stores", "0006_store_store_phone_number_store_store_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        default=stores.models.generate_store_profile_id,
                        max_length=8,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                (
                    "store",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="stores.store",
                    ),
                ),
            ],
        ),
    ]
